package org.apache.camel.quarkus.component.irc.foo;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import org.junit.jupiter.api.Test;

@QuarkusTest
class FooTest {

    @Test
    public void loadComponentFoo() {
        /* A simple autogenerated test */
        RestAssured.get("/irc/load/component/foo")
                .then()
                .statusCode(200);
    }

}